-- ============================================================================
-- lp_courses_SCHEMA.sql
-- DOCUMENTATION-ONLY reference for the "Learning Paths" course engine schema.
--
-- This schema was built ad-hoc via the Supabase SQL editor over time and had
-- NO checked-in migration file anywhere in the repo, even though all 20
-- app_lp_* RPCs that depend on it are registered in rpc_manifest.json. This
-- file closes that gap by recording live production reality (introspected
-- 2026-07-14 via information_schema.columns) as `create table if not exists`
-- statements. It is safe to run against prod (every table already exists,
-- so IF NOT EXISTS is a no-op) and safe to check in.
--
-- Do NOT treat this file as the source of truth to build from -- it's a
-- mirror of what's already live. If prod schema changes, re-introspect and
-- update this file to match; never let this file drift ahead of prod.
--
-- Six tables make up the engine:
--   learning_paths        - top-level path/catalog entries (e.g. "Crew Onboarding")
--   lp_courses             - individual courses within a path (lessons/pages/quiz/video)
--   lp_enrollments          - which employee is assigned to which path, due date, status
--   lp_assignment_rules     - auto-assign rules (e.g. "everyone with role=Crew gets path X")
--   lp_course_completions   - one row per course an employee has completed
--   lp_quiz_attempts        - one row per quiz attempt (superset of completions --
--                             records attempts even if the course itself doesn't
--                             end up "completed", useful for review/audit trails)
-- ============================================================================

create table if not exists public.learning_paths (
  id           bigint generated by default as identity primary key,
  title        text not null,
  description  text,
  target_role  text,
  level        text,
  icon         text,
  sort         integer default 0,
  active       boolean default true,
  created_by   text,
  created_at   timestamptz default now(),
  updated_at   timestamptz default now()
);

create table if not exists public.lp_courses (
  id                   bigint generated by default as identity primary key,
  path_id              bigint not null references public.learning_paths(id),
  title                text not null,
  summary              text,
  pages                jsonb default '[]'::jsonb,   -- lesson content blocks
  quiz                 jsonb default '[]'::jsonb,   -- quiz question definitions
  pass_pct             integer default 80,
  sort                 integer default 0,
  active               boolean default true,
  created_at           timestamptz default now(),
  updated_at           timestamptz default now(),
  video_url            text,
  materials            jsonb default '[]'::jsonb,   -- attached downloadable materials
  pub_status           text default 'published',    -- draft | published
  version              integer default 1,
  requires_retraining  boolean default false,
  scorm_url            text,                         -- pointer to uploaded SCORM package (if any)
  scorm_version        text default '1.2'            -- '1.2' | '2004'
);

create table if not exists public.lp_enrollments (
  id           bigint generated by default as identity primary key,
  path_id      bigint not null references public.learning_paths(id),
  employee_id  bigint not null,
  assigned_by  text,
  assigned_at  timestamptz default now(),
  due_date     date,
  status       text default 'assigned'   -- assigned | in_progress | completed | overdue
);

create table if not exists public.lp_assignment_rules (
  id                bigint generated by default as identity primary key,
  path_id           bigint not null references public.learning_paths(id),
  scope             text not null,        -- e.g. 'role', 'all', 'location'
  scope_value       text,
  due_offset_days   integer default 14,
  active            boolean default true,
  created_by        text,
  created_at        timestamptz default now()
);

create table if not exists public.lp_course_completions (
  id             bigint generated by default as identity primary key,
  employee_id    bigint not null,
  course_id      bigint not null references public.lp_courses(id),
  path_id        bigint references public.learning_paths(id),
  score          integer,
  passed         boolean default false,
  completed_at   timestamptz default now(),
  responses      jsonb default '[]'::jsonb
);

create table if not exists public.lp_quiz_attempts (
  id            bigint generated by default as identity primary key,
  employee_id   bigint,
  course_id     bigint,
  path_id       bigint,
  score         integer,
  passed        boolean,
  responses     jsonb default '[]'::jsonb,
  created_at    timestamptz default now()
);

-- ----------------------------------------------------------------------------
-- Known RPC surface (already live, already in rpc_manifest.json -- listed
-- here purely so this file is a complete map of the engine in one place):
--   app_lp_catalog, app_lp_my, app_lp_course, app_lp_complete, app_lp_attempts,
--   app_lp_responses, app_lp_team, app_lp_assign, app_lp_archive,
--   app_lp_save_course, app_lp_save_path, app_lp_set_status, app_lp_set_scorm,
--   app_lp_requirements_list, app_lp_requirements_save,
--   app_lp_rule_list, app_lp_rule_save, app_lp_rule_remove, app_lp_rules_run,
--   app_lp_gamify, app_lp_leaderboard, app_lp_promo
--
-- Confirmed signature (via pg_get_function_arguments, 2026-07-14):
--   app_lp_complete(p_username text, p_password text, p_course_id bigint,
--                    p_score integer, p_passed boolean,
--                    p_responses jsonb default '[]'::jsonb) returns jsonb
--   -- NOTE: score/passed are supplied BY THE CLIENT and stored as given.
--   -- The grading logic lives entirely in the frontend (lmsSubmitQuiz, in
--   -- js/08_availability.js), not in this RPC. See lp_review_queue.sql for
--   -- the additive fix that routes long-answer-only quizzes to manager
--   -- review instead of letting the client auto-pass them.
-- ============================================================================
