-- ============================================================================
-- lp_review_queue.sql
-- Phase 1.3 of the training top-tier plan (specs/PLAN_scorm_training_topTier.md):
-- fixes the long-answer-only quiz auto-pass bug WITHOUT touching app_lp_complete.
--
-- THE BUG (frontend, js/08_availability.js, lmsSubmitQuiz()):
--   score = gradable>0 ? round(100*correct/gradable) : 100
-- A quiz made entirely of long-answer questions has gradable=0, so this
-- silently auto-passes at 100% regardless of what the employee actually
-- wrote. Confirmed via introspection (2026-07-14) that app_lp_complete's
-- score/passed args are fully client-supplied and stored as given -- it's a
-- thin trusted insert, not a grader. That RPC is untouched by this file and
-- keeps working exactly as before for every quiz that has at least one real
-- auto-gradable question (the vast majority).
--
-- THE FIX: when a quiz has zero auto-gradable questions, the frontend calls
-- app_lp_submit_review() instead of app_lp_complete(). That parks the
-- attempt in lp_pending_reviews for a manager to actually read and decide,
-- instead of the client fabricating a pass. Approval performs the same two
-- writes app_lp_complete performs (confirmed via introspection: it inserts
-- into lp_quiz_attempts + lp_course_completions and updates lp_enrollments),
-- so an approved review ends up identical to a normal completion record.
--
-- 100% additive: new table, new RPCs, zero changes to any existing table,
-- RPC, or the normal (has-gradable-questions) quiz path.
-- ============================================================================

create table if not exists public.lp_pending_reviews (
  id            bigint generated by default as identity primary key,
  employee_id   bigint not null,
  employee_name text,
  course_id     bigint not null references public.lp_courses(id),
  path_id       bigint references public.learning_paths(id),
  responses     jsonb default '[]'::jsonb,
  submitted_at  timestamptz default now(),
  status        text default 'pending',   -- pending | approved | rejected
  reviewed_by   text,
  reviewed_at   timestamptz,
  final_score   integer,
  review_note   text
);
create index if not exists lp_pending_reviews_status_idx on public.lp_pending_reviews(status, submitted_at);
create index if not exists lp_pending_reviews_employee_idx on public.lp_pending_reviews(employee_id, course_id);

-- Employee: submit a long-answer-only quiz attempt for manager review
-- instead of auto-completing it client-side.
create or replace function public.app_lp_submit_review(
  p_username text, p_password text, p_course_id bigint, p_responses jsonb default '[]'::jsonb
) returns jsonb
language plpgsql security definer set search_path=public,extensions
as $fn$
declare v_uid bigint; v_role text; v_name text; v_path_id bigint;
begin
  select uid,urole,uname into v_uid,v_role,v_name from public._pp_auth(p_username,p_password);
  if v_uid is null then raise exception 'forbidden'; end if;

  select path_id into v_path_id from public.lp_courses where id=p_course_id;
  if v_path_id is null then raise exception 'course not found'; end if;

  -- one open review per employee/course at a time -- resubmitting while
  -- pending just refreshes the existing row instead of piling up duplicates
  update public.lp_pending_reviews
     set responses = coalesce(p_responses,'[]'::jsonb), submitted_at = now()
   where employee_id = v_uid and course_id = p_course_id and status = 'pending';

  if not found then
    insert into public.lp_pending_reviews(employee_id, employee_name, course_id, path_id, responses, status)
    values (v_uid, v_name, p_course_id, v_path_id, coalesce(p_responses,'[]'::jsonb), 'pending');
  end if;

  return jsonb_build_object('ok', true, 'status', 'pending_review');
end $fn$;

-- Employee: see the status of their own submitted-for-review attempts (so
-- "My Training" can show "awaiting review" / "approved" / "sent back"
-- instead of the course just silently never completing).
create or replace function public.app_lp_my_reviews(
  p_username text, p_password text
) returns jsonb
language plpgsql security definer set search_path=public,extensions
as $fn$
declare v_uid bigint; v_role text; v_name text;
begin
  select uid,urole,uname into v_uid,v_role,v_name from public._pp_auth(p_username,p_password);
  if v_uid is null then raise exception 'forbidden'; end if;

  return coalesce((
    select jsonb_agg(jsonb_build_object(
      'id', r.id, 'course_id', r.course_id, 'course_title', c.title,
      'status', r.status, 'submitted_at', r.submitted_at,
      'reviewed_at', r.reviewed_at, 'review_note', r.review_note
    ) order by r.submitted_at desc)
    from public.lp_pending_reviews r
    left join public.lp_courses c on c.id = r.course_id
    where r.employee_id = v_uid
  ), '[]'::jsonb);
end $fn$;

-- Manager: list pending reviews awaiting a decision.
create or replace function public.app_lp_review_list(
  p_username text, p_password text
) returns jsonb
language plpgsql security definer set search_path=public,extensions
as $fn$
declare v_uid bigint; v_role text; v_name text;
begin
  select uid,urole,uname into v_uid,v_role,v_name from public._pp_auth(p_username,p_password);
  if v_uid is null then raise exception 'forbidden'; end if;
  if not (v_role ilike '%manager%' or v_role ilike '%admin%' or v_role ilike '%lead%'
          or v_role ilike '%owner%' or v_role ilike '%VP%' or v_role ilike '%office%') then
    raise exception 'forbidden'; end if;

  return coalesce((
    select jsonb_agg(jsonb_build_object(
      'id', r.id, 'employee_id', r.employee_id, 'employee_name', r.employee_name,
      'course_id', r.course_id, 'course_title', c.title,
      'path_id', r.path_id, 'path_title', lp.title,
      'responses', r.responses, 'submitted_at', r.submitted_at, 'status', r.status
    ) order by r.submitted_at asc)
    from public.lp_pending_reviews r
    left join public.lp_courses c on c.id = r.course_id
    left join public.learning_paths lp on lp.id = r.path_id
    where r.status = 'pending'
  ), '[]'::jsonb);
end $fn$;

-- Manager: approve or reject a pending long-answer review. On approval,
-- writes the exact same two rows app_lp_complete would have written, so the
-- employee's record is indistinguishable from a normal completion -- it just
-- required a human to actually read the answers first.
create or replace function public.app_lp_review_decide(
  p_username text, p_password text, p_review_id bigint,
  p_approve boolean, p_score integer default null, p_note text default null
) returns jsonb
language plpgsql security definer set search_path=public,extensions
as $fn$
declare v_uid bigint; v_role text; v_name text; r record; v_score integer;
begin
  select uid,urole,uname into v_uid,v_role,v_name from public._pp_auth(p_username,p_password);
  if v_uid is null then raise exception 'forbidden'; end if;
  if not (v_role ilike '%manager%' or v_role ilike '%admin%' or v_role ilike '%lead%'
          or v_role ilike '%owner%' or v_role ilike '%VP%' or v_role ilike '%office%') then
    raise exception 'forbidden'; end if;

  select * into r from public.lp_pending_reviews where id = p_review_id and status = 'pending';
  if r.id is null then raise exception 'review not found or already decided'; end if;

  v_score := coalesce(p_score, case when p_approve then 100 else 0 end);

  update public.lp_pending_reviews
     set status = case when p_approve then 'approved' else 'rejected' end,
         reviewed_by = v_name, reviewed_at = now(),
         final_score = v_score, review_note = p_note
   where id = p_review_id;

  if p_approve then
    insert into public.lp_quiz_attempts(employee_id, course_id, path_id, score, passed, responses)
    values (r.employee_id, r.course_id, r.path_id, v_score, true, r.responses);

    insert into public.lp_course_completions(employee_id, course_id, path_id, score, passed, responses)
    values (r.employee_id, r.course_id, r.path_id, v_score, true, r.responses)
    on conflict do nothing;

    update public.lp_enrollments
       set status = 'completed'
     where employee_id = r.employee_id and path_id = r.path_id and status <> 'completed';
  end if;

  return jsonb_build_object('ok', true, 'status', case when p_approve then 'approved' else 'rejected' end);
end $fn$;
