-- ============================================================================
-- lp_video_progress.sql
-- Phase 1.5 of the training top-tier plan: server-sync course video watch
-- progress. Additive only -- existing localStorage-based tracking (cvw_w_*,
-- cvw_d_*, cvw_pos_* keys in js/08_availability.js) is left completely in
-- place and keeps working exactly as before on the device that set it. This
-- adds a server-side mirror so progress also survives a cleared cache or
-- shows up on a second device, without changing the watch-gate logic itself.
-- ============================================================================

create table if not exists public.lp_video_progress (
  id                bigint generated by default as identity primary key,
  employee_id       bigint not null,
  video_key         text not null,
  course_id         bigint references public.lp_courses(id),
  watched_seconds   numeric default 0,
  duration_seconds  numeric default 0,
  updated_at        timestamptz default now(),
  unique (employee_id, video_key)
);
create index if not exists lp_video_progress_employee_idx on public.lp_video_progress(employee_id);

-- Employee: upsert progress for one video. Called on a client-side throttle
-- (~every 8s while playing, plus once on completion) -- never on every
-- timeupdate tick, to keep this cheap.
create or replace function public.app_lp_video_progress_save(
  p_username text, p_password text, p_video_key text, p_course_id bigint default null,
  p_watched numeric default 0, p_duration numeric default 0
) returns jsonb
language plpgsql security definer set search_path=public,extensions
as $fn$
declare v_uid bigint; v_role text; v_name text;
begin
  select uid,urole,uname into v_uid,v_role,v_name from public._pp_auth(p_username,p_password);
  if v_uid is null then raise exception 'forbidden'; end if;

  insert into public.lp_video_progress(employee_id, video_key, course_id, watched_seconds, duration_seconds, updated_at)
  values (v_uid, p_video_key, p_course_id, coalesce(p_watched,0), coalesce(p_duration,0), now())
  on conflict (employee_id, video_key)
  do update set
    course_id = coalesce(excluded.course_id, public.lp_video_progress.course_id),
    watched_seconds = greatest(public.lp_video_progress.watched_seconds, excluded.watched_seconds),
    duration_seconds = greatest(public.lp_video_progress.duration_seconds, excluded.duration_seconds),
    updated_at = now();

  return jsonb_build_object('ok', true);
end $fn$;

-- Employee: fetch all known video progress so a fresh device/browser can
-- seed localStorage instead of starting every video from zero.
create or replace function public.app_lp_video_progress_get(
  p_username text, p_password text
) returns jsonb
language plpgsql security definer set search_path=public,extensions
as $fn$
declare v_uid bigint; v_role text; v_name text;
begin
  select uid,urole,uname into v_uid,v_role,v_name from public._pp_auth(p_username,p_password);
  if v_uid is null then raise exception 'forbidden'; end if;

  return coalesce((
    select jsonb_object_agg(video_key, jsonb_build_object('watched', watched_seconds, 'duration', duration_seconds))
    from public.lp_video_progress
    where employee_id = v_uid
  ), '{}'::jsonb);
end $fn$;
